name: Go Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  go-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/core  # Все Go-файлы находятся в этой директории

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Initialize Go module
      run: |
        go mod init github.com/mamoedus/devsectest
        go mod tidy
    
    - name: Download dependencies
      run: |
        go get github.com/Nerzal/gocloak/v13
        go get gorm.io/gorm
        go get github.com/gin-gonic/gin
        go get github.com/aws/aws-sdk-go
        go mod download
    
    - name: Install security tools
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    
    - name: Run gosec (security audit)
      run: |
        gosec -exclude=G104 -fmt=json -out=gosec-report.json ./...
        echo "GOSEC_EXIT_CODE=$?" >> $GITHUB_ENV
    
    - name: Run golangci-lint (code quality)
      run: |
        golangci-lint run --out-format=colored-line-number --timeout=5m ./...
        echo "LINT_EXIT_CODE=$?" >> $GITHUB_ENV
    
    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: go-security-reports
        path: |
          gosec-report.json
