name: Full Security Scan

on:
  push:
    branches: [devsec]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  go-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run golangci-lint (full scan)
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run ./... --out-format=github-actions
        
    - name: Run gosec (full scan)
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec -fmt=sonarqube ./... > gosec-report.json || true
        
    - name: Upload gosec report
      uses: actions/upload-artifact@v3
      with:
        name: gosec-report
        path: gosec-report.json

  python-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Run Bandit (full scan)
      run: |
        pip install bandit
        bandit -r PolyPrep/ -f json -o bandit-report.json || true
        
    - name: Run Safety (full scan)
      run: |
        pip install safety
        safety check --json --output safety-report.json || true
        
    - name: Upload Python reports
      uses: actions/upload-artifact@v3
      with:
        name: python-reports
        path: |
          bandit-report.json
          safety-report.json

  js-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run npm audit (full scan)
      working-directory: ./PolyPrep/static/js
      run: |
        npm install
        npm audit --json > npm-audit.json || true
        
    - name: Run Snyk (full scan)
      working-directory: ./PolyPrep/static/js
      run: |
        npm install -g snyk
        snyk test --json > snyk-report.json || true
        
    - name: Upload JS reports
      uses: actions/upload-artifact@v3
      with:
        name: js-reports
        path: |
          PolyPrep/static/js/npm-audit.json
          PolyPrep/static/js/snyk-report.json
