name: Full Security Scan

on:
  push:
    branches: [devsec]
  workflow_dispatch:

jobs:
  go-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install tools
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install github.com/securego/gosec/v2/cmd/gosec@latest
    
    - name: Run golangci-lint
      run: golangci-lint run ./... --out-format=github-actions
        
    - name: Run gosec
      run: gosec -fmt=json ./... > gosec-report.json || true
        
    - name: Upload report
      uses: actions/upload-artifact@v4  # Используем версию v4
      with:
        name: go-security-report
        path: gosec-report.json

  python-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install tools
      run: |
        pip install bandit safety
    
    - name: Run Bandit
      run: bandit -r PolyPrep/ -f json -o bandit-report.json || true
        
    - name: Run Safety
      run: safety check --json --output safety-report.json || true
        
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: python-security-reports
        path: |
          bandit-report.json
          safety-report.json

  js-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: ./PolyPrep/static/js
      run: npm install
    
    - name: Run npm audit
      working-directory: ./PolyPrep/static/js
      run: npm audit --json > npm-audit.json || true
        
    - name: Run Snyk
      working-directory: ./PolyPrep/static/js
      run: |
        npm install -g snyk
        snyk test --json > snyk-report.json || true
        
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: js-security-reports
        path: |
          npm-audit.json
          snyk-report.json
